spring.application.name=URL_SHORTENER

# App
app.base-url=http://localhost:8080
app.default-expiry-in-days=30

spring.docker.compose.lifecycle-management=start_only
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://localhost:5432/shortner
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.datasource.hikari.connection-init-sql=SET TIME ZONE 'UTC'
spring.jpa.open-in-view=false

# Optional (debug)
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true


spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration